<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Kevin Jia" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.79.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              
<link href="../../rmarkdown-libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="../../rmarkdown-libs/anchor-sections/anchor-sections.js"></script>


<div id="modeling" class="section level1">
<h1>Modeling</h1>
<div id="instructions" class="section level2">
<h2>Instructions</h2>
<p>A knitted R Markdown document (preferably HTML) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on the due date. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). Knit an html copy too, for later! In the .Rmd file for Project 2, you can copy the first code-chunk into your project .Rmd file to get better formatting. Notice that you can adjust the opts_chunk$set(...) above to set certain parameters if necessary to make the knitting cleaner (you can globally set the size of all plots, etc). You can copy the set-up chunk in Project2.Rmd: I have gone ahead and set a few for you (such as disabling warnings and package-loading messges when knitting)!</p>
<p>Like before, I envision your written text forming something of a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be graded. Furthermore, all code contained in our project document should work properly. Please do not include any extraneous code or code which produces error messages. (Code which produces warnings is fine as long as you understand what the warnings mean.)</p>
</div>
<div id="find-data" class="section level2">
<h2>Find data:</h2>
<p>Find one dataset with at least 5 variables (ideally more!) that you want to use to build models/test hypotheses. At least one should be categorical (with 2-5 groups, ideally; definitely fewer than 10) and at least two should be numeric (taking on more than 10 distinct values). Ideally, at least of your variables will be binary (if not, you will have to create one by discretizing a numeric or collapsing levels of a categorical). You will need a minimum of 40 observations (<em>at least</em> 10 observations for every explanatory variable you have, ideally 20+ observations/variable).</p>
<p>It is perfectly fine to use either dataset (or the merged dataset, or a subset of your variables) from Project 1. However, I might encourage you to diversify things a bit and choose a different dataset to work with (particularly if the variables did not reveal interesting associations in Project 1 that you want to follow up with). The only requirement/restriction is that you may not use data from any examples we have done in class or lab. It would be a good idea to pick more cohesive data this time around (i.e., variables that you actually thing might have a relationship you would want to test). Think more along the lines of your Biostats project.</p>
<p>Again, you can use data from anywhere you want (see bottom for resources)! If you want a quick way to see whether a built-in (R) dataset has binary and/or character (i.e., categorical) variables, check out this list: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
</div>
<div id="guidelines-and-rubric" class="section level2">
<h2>Guidelines and Rubric</h2>
<ul>
<li><strong>0. (5 pts)</strong> Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph. What are they measuring? How many observations?</li>
</ul>
<pre class="r"><code>life_expectancy_tidy &lt;- read.csv(&quot;https://drive.google.com/uc?export=download&amp;id=1eAh-MFQd2kV3R6rUXyQPDgUzkDwbKDcd&quot;)</code></pre>
<p>My dataset describes the life expectancy of each country from 2000 - 2015. The dataset includes the variables year, status, life.expectancy, alcohol, schooling and many other variables. The year variable describes the year the data was collected for the respective country. The status variable describes whether or not the country is developing or developed. The life expectancy measures the life expectancy for the respective country for the corresponding year. The alcohol variable measures the alcohol consumption in litres per capita for the corresponding year. The schooling variable measures the number of years of schooling on average for the country for the corresponding year. There are 2938 observations for each variable.</p>
<ul>
<li><strong>1. (15 pts)</strong> Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all is unreasonable or doesn't make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss MANOVA assumptions and whether or not they are likely to have been met (no need for anything too in-depth) (2).</li>
</ul>
<pre class="r"><code>library(dplyr)
library(mvtnorm)
library(ggExtra)

le &lt;- life_expectancy_tidy
set.seed(1234)
dplyr::sample_n(le, 10)</code></pre>
<pre><code>## Country Year Status Life.expectancy
## 1 Germany 2006 Developed 79.6
## 2 Congo 2001 Developing 52.7
## 3 Turkey 2004 Developing 72.0
## 4 France 2012 Developing 81.5
## 5 Bulgaria 2000 Developed 71.1
## 6 Russian Federation 2005 Developing 65.0
## 7 United Kingdom of Great Britain and Northern Ireland
2004 Developed 78.8
## 8 Mali 2008 Developing 55.5
## 9 Solomon Islands 2003 Developing 66.8
## 10 Guinea-Bissau 2003 Developing 53.0
## Adult.Mortality infant.deaths Alcohol
percentage.expenditure Hepatitis.B Measles BMI
## 1 84 3 11.76 6407.535954 87 2307 58.0
## 2 419 9 2.30 0.000000 NA 2152 19.8
## 3 132 33 1.35 1.132767 77 8927 56.8
## 4 83 3 11.50 751.379355 78 0 61.1
## 5 163 1 9.69 15.235727 94 46 57.0
## 6 327 18 11.57 625.508180 97 454 55.3
## 7 83 4 12.22 0.000000 NA 189 6.1
## 8 278 55 0.57 102.141374 74 98 19.6
## 9 215 0 1.18 16.831706 79 0 4.4
## 10 38 5 2.16 2.527115 NA 1158 19.0
## under.five.deaths Polio Total.expenditure Diphtheria
HIV.AIDS GDP Population
## 1 3 94 1.34 96 0.1 36447.87232 82376451
## 2 14 32 2.44 31 7.6 NA NA
## 3 39 85 5.37 85 0.1 64.72953 677855
## 4 3 99 11.44 99 0.1 4838.24440 6565979
## 5 1 94 6.70 93 0.1 169.28586 817172
## 6 20 98 5.21 98 0.3 5323.47388 143518523
## 7 4 92 7.98 92 0.1 NA NA
## 8 94 74 6.74 74 1.6 689.67842 14138216
## 9 0 84 6.00 84 0.1 744.76574 446769
## 10 8 65 5.62 6 4.6 36.57186 132122
## thinness..1.19.years thinness.5.9.years
Income.composition.of.resources Schooling
## 1 1.1 1.1 0.892 16.5
## 2 9.4 9.0 0.487 9.7
## 3 5.1 4.9 0.675 12.0
## 4 0.6 0.6 0.885 16.1
## 5 2.5 2.5 0.709 12.9
## 6 2.4 2.7 0.748 13.7
## 7 0.7 0.5 NA NA
## 8 9.2 9.0 0.360 5.8
## 9 1.3 1.3 0.453 8.0
## 10 9.6 9.5 0.000 7.4</code></pre>
<pre class="r"><code>#MANOVA test

man1&lt;-manova(cbind(Life.expectancy, Alcohol, Schooling)~Status, data=le)
summary(man1)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## Status 1 0.42315 630.87 3 2580 &lt; 2.2e-16 ***
## Residuals 2582
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man1)</code></pre>
<pre><code>## Response Life.expectancy :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Status 1 51546 51546 756.72 &lt; 2.2e-16 ***
## Residuals 2582 175881 68
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response Alcohol :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Status 1 14216 14216.2 1346.2 &lt; 2.2e-16 ***
## Residuals 2582 27266 10.6
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response Schooling :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Status 1 7634.7 7634.7 982.58 &lt; 2.2e-16 ***
## Residuals 2582 20062.3 7.8
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## 354 observations deleted due to missingness</code></pre>
<pre class="r"><code>pairwise.t.test(le$Life.expectancy, le$Status, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  le$Life.expectancy and le$Status 
## 
##            Developed
## Developing &lt;2e-16   
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(le$Alcohol, le$Status, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  le$Alcohol and le$Status 
## 
##            Developed
## Developing &lt;2e-16   
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(le$Schooling, le$Status, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  le$Schooling and le$Status 
## 
##            Developed
## Developing &lt;2e-16   
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>#Type I error rate = 0.3016627
1-0.95^7</code></pre>
<pre><code>## [1] 0.3016627</code></pre>
<pre class="r"><code>#Bonferroni correction = 0.007142857
0.05/7</code></pre>
<pre><code>## [1] 0.007142857</code></pre>
<p>The overall MANOVA is significant. 1 MANOVA, 3 ANOVA and 3 t tests were performed. The probability of at least one type I error is 0.3016627 and adjusting the significance level accordingly (bonferroni correction) is 0.007142857. Developing vs developed countries seem to differ significantly in terms of life expectancy, alcohol consumption and schooling. MANOVA assumptions include random samples, independent observations, multivariate normality of DVs, homogeneity of within-group covariance matrices, linear relationships among DVs, no extreme univariate or multivariate outliers, and no multicollinearity (i.e., DVs should not be too correlated). These assumptions are not likely to be met.</p>
<ul>
<li><strong>2. (10 pts)</strong> Perform some kind of randomization test on your data (that makes sense). The statistic can be anything you want (mean difference, correlation, F-statistic/ANOVA, chi-squared), etc. State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).</li>
</ul>
<pre class="r"><code>library(tidyverse)
set.seed(348)

head(le) </code></pre>
<pre><code>## Country Year Status Life.expectancy Adult.Mortality
infant.deaths Alcohol
## 1 Afghanistan 2015 Developing 65.0 263 62 0.01
## 2 Afghanistan 2014 Developing 59.9 271 64 0.01
## 3 Afghanistan 2013 Developing 59.9 268 66 0.01
## 4 Afghanistan 2012 Developing 59.5 272 69 0.01
## 5 Afghanistan 2011 Developing 59.2 275 71 0.01
## 6 Afghanistan 2010 Developing 58.8 279 74 0.01
## percentage.expenditure Hepatitis.B Measles BMI
under.five.deaths Polio Total.expenditure
## 1 71.279624 65 1154 19.1 83 6 8.16
## 2 73.523582 62 492 18.6 86 58 8.18
## 3 73.219243 64 430 18.1 89 62 8.13
## 4 78.184215 67 2787 17.6 93 67 8.52
## 5 7.097109 68 3013 17.2 97 68 7.87
## 6 79.679367 66 1989 16.7 102 66 9.20
## Diphtheria HIV.AIDS GDP Population thinness..1.19.years
thinness.5.9.years
## 1 65 0.1 584.25921 33736494 17.2 17.3
## 2 62 0.1 612.69651 327582 17.5 17.5
## 3 64 0.1 631.74498 31731688 17.7 17.7
## 4 67 0.1 669.95900 3696958 17.9 18.0
## 5 68 0.1 63.53723 2978599 18.2 18.2
## 6 66 0.1 553.32894 2883167 18.4 18.4
## Income.composition.of.resources Schooling
## 1 0.479 10.1
## 2 0.476 10.0
## 3 0.470 9.9
## 4 0.463 9.8
## 5 0.454 9.5
## 6 0.448 9.2</code></pre>
<pre class="r"><code>le%&gt;%group_by(Status)%&gt;%
  summarize(means=mean(Year))%&gt;%summarize(`mean_diff`=diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   mean_diff
##       &lt;dbl&gt;
## 1    0.0227</code></pre>
<pre class="r"><code>rand_dist&lt;-vector() #create vector to hold diffs under null hypothesis

for(i in 1:5000){
new&lt;-data.frame(Year=sample(le$Year),Status=le$Status) #scramble columns
rand_dist[i]&lt;-mean(new[new$Status==&quot;Developed&quot;,]$Year)-   
              mean(new[new$Status==&quot;Developing&quot;,]$Year)} #compute mean difference (base R)

{hist(rand_dist,main=&quot;&quot;,ylab=&quot;&quot;); abline(v = c(-0.02267106, 0.02267106),col=&quot;red&quot;)}</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>mean(rand_dist&gt;0.02267106 | rand_dist&lt; -0.02267106) #two-tailed p value</code></pre>
<pre><code>## [1] 0.9188</code></pre>
<pre class="r"><code>t.test(data=le,Year~Status)</code></pre>
<pre><code>##
## Welch Two Sample t-test
##
## data: Year by Status
## t = -0.10102, df = 742.53, p-value = 0.9196
## alternative hypothesis: true difference in means is not
equal to 0
## 95 percent confidence interval:
## -0.4632389 0.4178968
## sample estimates:
## mean in group Developed mean in group Developing
## 2007.500 2007.523</code></pre>
<p>H0: mean amount of alcohol consumption is the same for developing vs developed countries HA: mean amount of alcohol consumption is different for developing vs developed countries The p-value of 0.9196 indicates that the test is not statistically significant and indicates strong evidence for the null hypothesis. Thus we fail to reject the null hypothesis and reject the alternative hypothesis.</p>
<ul>
<li><p><strong>3. (35 pts)</strong> Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction.</p>
<ul>
<li>Interpret the coefficient estimates (do not discuss significance) (10)</li>
<li>Plot the regression using <code>ggplot()</code> using geom_smooth(method=&quot;lm&quot;). If your interaction is numeric by numeric, refer to code in the slides to make the plot or check out the <code>interactions</code> package, which makes this easier. If you have 3 or more predictors, just chose two of them to plot for convenience. (8)</li>
<li>Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (4)</li>
<li>Regardless, recompute regression results with robust standard errors via <code>coeftest(..., vcov=vcovHC(...))</code>. Discuss significance of results, including any changes from before/after robust SEs if applicable. (8)</li>
<li>What proportion of the variation in the outcome does your model explain? (4)</li>
</ul></li>
</ul>
<pre class="r"><code>library(lmtest)
library(sandwich)

fit&lt;-lm(Life.expectancy ~ Alcohol + Schooling, data=le)
summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = Life.expectancy ~ Alcohol + Schooling, data
= le)
##
## Residuals:
## Min 1Q Median 3Q Max
## -25.394 -2.908 0.636 3.897 32.039
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 43.30759 0.48442 89.400 &lt;2e-16 ***
## Alcohol -0.09159 0.03664 -2.499 0.0125 *
## Schooling 2.19926 0.04485 49.040 &lt;2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 6.243 on 2581 degrees of
freedom
## (354 observations deleted due to missingness)
## Multiple R-squared: 0.5577, Adjusted R-squared: 0.5573
## F-statistic: 1627 on 2 and 2581 DF, p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>ggplot(le, aes(x=Alcohol + Schooling, y=Life.expectancy,group=Status))+geom_point(aes(color=Status))+
geom_smooth(method=&quot;lm&quot;,formula=y~1,se=F,fullrange=T,aes(color=Status))+
theme(legend.position=c(.9,.19))+xlab(&quot;&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>resids&lt;-fit$residuals
fitvals&lt;-fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, color=&#39;red&#39;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>par(mfrow=c(1,2)); hist(resids); qqnorm(resids); qqline(resids, col=&#39;red&#39;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>coeftest(fit, vcov = vcovHC(fit)) #regression after adjusting standard errors for violation</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 43.307586 0.852914 50.7760 &lt; 2e-16 ***
## Alcohol -0.091589 0.045375 -2.0185 0.04364 *
## Schooling 2.199264 0.078541 28.0014 &lt; 2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = Life.expectancy ~ Alcohol + Schooling, data
= le)
##
## Residuals:
## Min 1Q Median 3Q Max
## -25.394 -2.908 0.636 3.897 32.039
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 43.30759 0.48442 89.400 &lt;2e-16 ***
## Alcohol -0.09159 0.03664 -2.499 0.0125 *
## Schooling 2.19926 0.04485 49.040 &lt;2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 6.243 on 2581 degrees of
freedom
## (354 observations deleted due to missingness)
## Multiple R-squared: 0.5577, Adjusted R-squared: 0.5573
## F-statistic: 1627 on 2 and 2581 DF, p-value: &lt; 2.2e-16</code></pre>
<p>The coefficient estimate for Alcohol indicate that for every litre of alcohol drunk on average life expectancy changes by -0.09159. The coefficient estimate for Schooling indicates that for each year of schooling, life expectancy increases by 2.19926. The standard error for the intercept is 0.48442, the standard error for Alcohol is 0.03664, and the standard error for Schooling is 0.04485. From the graph, it appears that linearity, normality, and homoskedasticity look ok. The standard error did differ. The new standard error for the intercept is 0.852914, the new standard error for Alcohol is 0.045375, and the standard error for Schooling is 0.078541. The proportion of the variation in the outcome my model explains is 0.5573.</p>
<ul>
<li><strong>4. (5 pts)</strong> Rerun same regression model (with the interaction), but this time compute bootstrapped standard errors (either by resampling observations or residuals). Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)</li>
</ul>
<pre class="r"><code>boot_dat&lt;- sample_frac(le, replace=T)

samp_distn&lt;-replicate(5000, {
  boot_dat &lt;- sample_frac(le, replace=T)
  fit &lt;- lm(Life.expectancy ~ Alcohol + Schooling, data=boot_dat)
  coef(fit) 
}) 
 
samp_distn %&gt;% t %&gt;% as.data.frame %&gt;% summarize_all(sd) </code></pre>
<pre><code>##   (Intercept)    Alcohol  Schooling
## 1   0.8224301 0.04509203 0.07602908</code></pre>
<p>The new intercept is 0.8368392, the new standard error for Alcohol is 0.04433427, and the new standard arror for Schooling is 0.07665198.</p>
<ul>
<li><p><strong>5. (25 pts)</strong> Fit a logistic regression model predicting a binary variable (if you don't have one, make/get one) from at least two explanatory variables (interaction not necessary).</p>
<ul>
<li>Interpret coefficient estimates in context (10)</li>
<li>Report a confusion matrix for your logistic regression (2)</li>
<li>Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), Precision (PPV), and AUC of your model (5)</li>
<li>Using ggplot, make a density plot of the log-odds (logit) colored/grouped by your binary outcome variable (3)</li>
<li>Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (5)</li>
</ul></li>
</ul>
<pre class="r"><code>library(tidyverse)
library(lmtest)
library(plotROC)

data&lt;-le%&gt;%mutate(y=ifelse(Status==&quot;Developed&quot;,1,0))
data$Status&lt;-factor(data$Status,levels=c(&quot;Developed&quot;,&quot;Developing&quot;)) 
head(data)</code></pre>
<pre><code>## Country Year Status Life.expectancy Adult.Mortality
infant.deaths Alcohol
## 1 Afghanistan 2015 Developing 65.0 263 62 0.01
## 2 Afghanistan 2014 Developing 59.9 271 64 0.01
## 3 Afghanistan 2013 Developing 59.9 268 66 0.01
## 4 Afghanistan 2012 Developing 59.5 272 69 0.01
## 5 Afghanistan 2011 Developing 59.2 275 71 0.01
## 6 Afghanistan 2010 Developing 58.8 279 74 0.01
## percentage.expenditure Hepatitis.B Measles BMI
under.five.deaths Polio Total.expenditure
## 1 71.279624 65 1154 19.1 83 6 8.16
## 2 73.523582 62 492 18.6 86 58 8.18
## 3 73.219243 64 430 18.1 89 62 8.13
## 4 78.184215 67 2787 17.6 93 67 8.52
## 5 7.097109 68 3013 17.2 97 68 7.87
## 6 79.679367 66 1989 16.7 102 66 9.20
## Diphtheria HIV.AIDS GDP Population thinness..1.19.years
thinness.5.9.years
## 1 65 0.1 584.25921 33736494 17.2 17.3
## 2 62 0.1 612.69651 327582 17.5 17.5
## 3 64 0.1 631.74498 31731688 17.7 17.7
## 4 67 0.1 669.95900 3696958 17.9 18.0
## 5 68 0.1 63.53723 2978599 18.2 18.2
## 6 66 0.1 553.32894 2883167 18.4 18.4
## Income.composition.of.resources Schooling y
## 1 0.479 10.1 0
## 2 0.476 10.0 0
## 3 0.470 9.9 0
## 4 0.463 9.8 0
## 5 0.454 9.5 0
## 6 0.448 9.2 0</code></pre>
<pre class="r"><code>data&lt;-na.omit(data)

fit2&lt;-glm(y~Life.expectancy+Alcohol, data=data, family=&quot;binomial&quot;)
coeftest(fit2)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -22.798666 1.859061 -12.2635 &lt; 2.2e-16 ***
## Life.expectancy 0.234702 0.023968 9.7923 &lt; 2.2e-16 ***
## Alcohol 0.487426 0.036559 13.3327 &lt; 2.2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>probs&lt;-predict(fit2,type=&quot;response&quot;)
table(predict=as.numeric(probs&gt;.5),truth=data$y)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict    0    1  Sum
##     0   1354   66 1420
##     1     53  176  229
##     Sum 1407  242 1649</code></pre>
<pre class="r"><code>class_diag &lt;- function(probs,truth){
  #CONFUSION MATRIX: CALCULATE ACCURACY, TPR, TNR, PPV
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]
  f1=2*(sens*ppv)/(sens+ppv)

  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  
  #CALCULATE EXACT AUC
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,f1,auc)
}

class_diag(probs, data$y)</code></pre>
<pre><code>## acc sens spec ppv f1 auc
## 1 0.9278351 0.7272727 0.9623312 0.768559 0.7473461
0.9632519</code></pre>
<pre class="r"><code>data$logit&lt;-predict(fit2,type=&quot;link&quot;)

data%&gt;%ggplot()+geom_density(aes(logit,color=Status,fill=Status), alpha=.4)+
  theme(legend.position=c(.85,.85))+geom_vline(xintercept=0)+xlab(&quot;logit (log-odds)&quot;)+
  geom_rug(aes(logit,color=Status))</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ROCplot&lt;-ggplot(data)+geom_roc(aes(d=Status,m=probs), n.cuts=0) 

ROCplot</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group        AUC
## 1     1    -1 0.03675395</code></pre>
<p>Because the coefficient estimates in context are positive for alcohol and negative for life expectancy, I can tell the two predictors significantly increase the probability of that a country is developing.</p>
<p>Accuracy=0.9278351 Sensitivity (TPR)=0.7272727 Specificity (TNR)=0.9623312 Precision (PPV)=0.768559 AUC=0.9632519</p>
<p>The AUC from the ROC plot is 0.03675395. The AUC decreased.</p>
<ul>
<li><p><strong>6. (25 pts)</strong> Perform a logistic regression predicting the same binary response variable from <em>ALL</em> of the rest of your variables (the more, the better!)</p>
<ul>
<li>Fit model, compute in-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, AUC), and interpret (5)</li>
<li>Perform 10-fold (or repeated random sub-sampling) CV with the same model and report average out-of-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, and AUC); interpret AUC and compare with the in-sample metrics (10)</li>
<li>Perform LASSO on the same model/variables. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., <code>lambda.1se</code>). Discuss which variables are retained. (5)</li>
<li>Perform 10-fold CV using only the variables lasso selected: compare model's out-of-sample AUC to that of your logistic regressions above (5)</li>
</ul></li>
</ul>
<pre class="r"><code>data&lt;-le%&gt;%mutate(y=ifelse(Status==&quot;Developed&quot;,1,0))
data$Status&lt;-factor(data$Status,levels=c(&quot;Developed&quot;,&quot;Developing&quot;)) 
head(data)</code></pre>
<pre><code>## Country Year Status Life.expectancy Adult.Mortality
infant.deaths Alcohol
## 1 Afghanistan 2015 Developing 65.0 263 62 0.01
## 2 Afghanistan 2014 Developing 59.9 271 64 0.01
## 3 Afghanistan 2013 Developing 59.9 268 66 0.01
## 4 Afghanistan 2012 Developing 59.5 272 69 0.01
## 5 Afghanistan 2011 Developing 59.2 275 71 0.01
## 6 Afghanistan 2010 Developing 58.8 279 74 0.01
## percentage.expenditure Hepatitis.B Measles BMI
under.five.deaths Polio Total.expenditure
## 1 71.279624 65 1154 19.1 83 6 8.16
## 2 73.523582 62 492 18.6 86 58 8.18
## 3 73.219243 64 430 18.1 89 62 8.13
## 4 78.184215 67 2787 17.6 93 67 8.52
## 5 7.097109 68 3013 17.2 97 68 7.87
## 6 79.679367 66 1989 16.7 102 66 9.20
## Diphtheria HIV.AIDS GDP Population thinness..1.19.years
thinness.5.9.years
## 1 65 0.1 584.25921 33736494 17.2 17.3
## 2 62 0.1 612.69651 327582 17.5 17.5
## 3 64 0.1 631.74498 31731688 17.7 17.7
## 4 67 0.1 669.95900 3696958 17.9 18.0
## 5 68 0.1 63.53723 2978599 18.2 18.2
## 6 66 0.1 553.32894 2883167 18.4 18.4
## Income.composition.of.resources Schooling y
## 1 0.479 10.1 0
## 2 0.476 10.0 0
## 3 0.470 9.9 0
## 4 0.463 9.8 0
## 5 0.454 9.5 0
## 6 0.448 9.2 0</code></pre>
<pre class="r"><code>data&lt;-na.omit(data)

fit3&lt;-glm(y~Life.expectancy + Adult.Mortality + infant.deaths + Alcohol + percentage.expenditure + 
Hepatitis.B + Measles + BMI + under.five.deaths + Polio + Total.expenditure + Diphtheria + 
HIV.AIDS + GDP + Population + thinness..1.19.years + thinness.5.9.years + Income.composition.of.resources + 
Schooling, data=data, family=&quot;binomial&quot;)
coeftest(fit3)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -4.9629e+00 3.1833e+02 -0.0156 0.9875611
## Life.expectancy -3.7001e-02 4.8496e-02 -0.7630 0.4454880
## Adult.Mortality -6.9611e-03 2.5232e-03 -2.7589 0.0057998
**
## infant.deaths 1.7151e-01 3.7352e-01 0.4592 0.6461100
## Alcohol 3.6737e-01 4.4214e-02 8.3089 &lt; 2.2e-16 ***
## percentage.expenditure -5.3540e-05 1.4142e-04 -0.3786
0.7049992
## Hepatitis.B 2.9210e-02 5.8480e-03 4.9948 5.891e-07 ***
## Measles 1.9812e-05 6.4136e-05 0.3089 0.7573957
## BMI 2.5154e-03 7.5201e-03 0.3345 0.7380143
## under.five.deaths -4.1642e-01 3.3303e-01 -1.2504
0.2111512
## Polio 1.0779e-02 1.2327e-02 0.8744 0.3818758
## Total.expenditure 1.7271e-02 5.1358e-02 0.3363 0.7366493
## Diphtheria -2.9987e-03 1.2832e-02 -0.2337 0.8152340
## HIV.AIDS -1.2521e+02 3.1831e+03 -0.0393 0.9686218
## GDP 1.5771e-06 2.2588e-05 0.0698 0.9443355
## Population 6.7730e-09 8.7935e-09 0.7702 0.4411684
## thinness..1.19.years -6.9499e-01 2.6663e-01 -2.6066
0.0091449 **
## thinness.5.9.years 7.1540e-01 2.5868e-01 2.7656
0.0056822 **
## Income.composition.of.resources 1.9149e+01 5.0455e+00
3.7952 0.0001475 ***
## Schooling -5.9376e-02 1.3327e-01 -0.4455 0.6559334
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>probs&lt;-predict(fit3,type=&quot;response&quot;)
table(predict=as.numeric(probs&gt;.5),truth=data$y)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict    0    1  Sum
##     0   1364   45 1409
##     1     43  197  240
##     Sum 1407  242 1649</code></pre>
<pre class="r"><code>class_diag(probs, data$y)</code></pre>
<pre><code>## acc sens spec ppv f1 auc
## 1 0.9466343 0.8140496 0.9694385 0.8208333 0.8174274
0.9781846</code></pre>
<pre class="r"><code>set.seed(1234)
k=10
data &lt;- le %&gt;% sample_frac #put rows of dataset in random order
folds &lt;- ntile(1:nrow(data),n=10) #create fold labels
diags&lt;-NULL
for(i in 1:k){
train &lt;- data[folds!=i,] #create training set (all but fold i)
test &lt;- data[folds==i,] #create test set (just fold i)
truth &lt;- test$Status #save truth labels from fold i
fit &lt;- glm(Status~Life.expectancy + Adult.Mortality + infant.deaths + Alcohol + percentage.expenditure + 
Hepatitis.B + Measles + BMI + under.five.deaths + Polio + Total.expenditure + Diphtheria + 
HIV.AIDS + GDP + Population + thinness..1.19.years + thinness.5.9.years + Income.composition.of.resources + 
Schooling, data=train, family=&quot;binomial&quot;)
probs &lt;- predict(fit, newdata=test, type=&quot;response&quot;)
diags&lt;-rbind(diags,class_diag(probs,truth))
}
summarize_all(diags,mean)</code></pre>
<pre><code>##         acc      sens      spec       ppv        f1 auc
## 1 0.9382767 0.9637796 0.7916945 0.9636347 0.9635994  NA</code></pre>
<pre class="r"><code>library(glmnet)

le1 &lt;- na.omit(le)

y&lt;-as.matrix(le1$Status) 
x&lt;-model.matrix(Status~Life.expectancy + Adult.Mortality + infant.deaths + Alcohol + percentage.expenditure + 
Hepatitis.B + Measles + BMI + under.five.deaths + Polio + Total.expenditure + Diphtheria + 
HIV.AIDS + GDP + Population + thinness..1.19.years + thinness.5.9.years + Income.composition.of.resources + 
Schooling,data=le)[,-1]
x &lt;- scale(x)

cv&lt;-cv.glmnet(x,y,family=&quot;binomial&quot;)
lasso1&lt;-glmnet(x,y,family=&quot;binomial&quot;,lambda=cv$lambda.1se)
coef(lasso1) </code></pre>
<pre><code>## 20 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                                          s0
## (Intercept)                      4.47135654
## Life.expectancy                 -0.43583879
## Adult.Mortality                  0.56418101
## infant.deaths                    .         
## Alcohol                         -1.45590127
## percentage.expenditure           .         
## Hepatitis.B                     -0.51641072
## Measles                          .         
## BMI                              .         
## under.five.deaths                .         
## Polio                            .         
## Total.expenditure               -0.01717151
## Diphtheria                       .         
## HIV.AIDS                         .         
## GDP                             -0.02422926
## Population                       .         
## thinness..1.19.years             .         
## thinness.5.9.years               .         
## Income.composition.of.resources -1.67841596
## Schooling                       -0.12461958</code></pre>
<pre class="r"><code>set.seed(1234)
k=10
data &lt;- le1 %&gt;% sample_frac 
folds &lt;- ntile(1:nrow(data),n=10) 
diags&lt;-NULL
for(i in 1:k){
train &lt;- data[folds!=i,] 
test &lt;- data[folds==i,] 
truth &lt;- test$Status 
fit &lt;- glm(Status~Life.expectancy + Adult.Mortality + infant.deaths + Alcohol + percentage.expenditure + 
Hepatitis.B + Measles + BMI + under.five.deaths + Polio + Total.expenditure + Diphtheria + 
HIV.AIDS + GDP + Population + thinness..1.19.years + thinness.5.9.years + Income.composition.of.resources + 
Schooling, data=train, family=&quot;binomial&quot;)
probs &lt;- predict(fit, newdata=test, type=&quot;response&quot;)
diags&lt;-rbind(diags,class_diag(probs,truth))
}
summarize_all(diags,mean)</code></pre>
<pre><code>## acc sens spec ppv f1 auc
## 1 0.9375388 0.9608035 0.8068669 0.9658007 0.9631091
0.9711832</code></pre>
<p>Fit model Accuracy=0.9466343 Sensitivity (TPR)=0.8140496 Specificity (TNR)=0.9694385 Precision (PPV)=0.8208333 AUC=0.9781846</p>
<p>Accuracy, Sensitivity, Specificity, Precision, and AUC all increased slightly.</p>
<p>CV model Accuracy=0.9382767 Sensitivity (TPR)=0.9637796 Specificity (TNR)=0.7916945 Precision (PPV)=0.9636347 AUC=NA</p>
<p>The AUC became NA, which is different from the AUC of 0.9781846 from the in-sample metrics.</p>
<p>The variables infant.deaths, Measles, BMI, under.five.deaths, Polio, Diphtheria, HIV.AIDS, Population, thinness..1.19.years, thinness.5.9.years are retained.</p>
<p>The AUC decreased slightly to 0.9711832.</p>
</div>
<div id="where-do-i-find-data-again" class="section level2">
<h2>Where do I find data again?</h2>
<p>You can choose ANY datasets you want that meet the above criteria for variables and observations. You can make it as serious as you want, or not, but keep in mind that you will be incorporating this project into a portfolio webpage for your final in this course, so choose something that really reflects who you are, or something that you feel will advance you in the direction you hope to move career-wise, or something that you think is really neat, or whatever. On the flip side, regardless of what you pick, you will be performing all the same tasks, so it doesn't end up being that big of a deal.</p>
<p>If you are totally clueless and have no direction at all, log into the server and type</p>
<pre class="r"><code>data(package = .packages(all.available = TRUE))</code></pre>
<p>This will print out a list of <strong>ALL datasets in ALL packages</strong> installed on the server (a ton)! Scroll until your eyes bleed! Actually, do not scroll that much... To start with something more manageable, just run the command on your own computer, or just run <code>data()</code> to bring up the datasets in your current environment. To read more about a dataset, do <code>?packagename::datasetname</code>.</p>
<p>If it is easier for you, and in case you don't have many packages installed, a list of R datasets from a few common packages (also downloadable in CSV format) is given at the following website: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
<ul>
<li><p>A good package to download for fun/relevant data is <code>fivethiryeight</code>. Run <code>install.packages(&quot;fivethirtyeight&quot;),</code> load the packages with <code>library(fivethirtyeight)</code>, run <code>data()</code>, and then scroll down to view the datasets. Here is an online list of all 127 datasets (with links to the 538 articles). Lots of sports, politics, current events, etc.</p></li>
<li><p>If you have already started to specialize (e.g., ecology, epidemiology) you might look at discipline-specific R packages (vegan, epi, respectively). We will be using some tools from these packages later in the course, but they come with lots of data too, which you can explore according to the directions above</p></li>
<li><p>However, you <em>emphatically DO NOT</em> have to use datasets available via R packages! In fact, I would much prefer it if you found the data from completely separate sources and brought them together (a much more realistic experience in the real world)! You can even reuse data from your SDS328M project, provided it shares a variable in common with other data which allows you to merge the two together (e.g., if you still had the timestamp, you could look up the weather that day: <a href="https://www.wunderground.com/history/" class="uri">https://www.wunderground.com/history/</a>). If you work in a research lab or have access to old data, you could potentially merge it with new data from your lab!</p></li>
<li><p>Here is a curated list of interesting datasets (read-only spreadsheet format): <a href="https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit" class="uri">https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit</a></p></li>
<li><p>Here is another great compilation of datasets: <a href="https://github.com/rfordatascience/tidytuesday" class="uri">https://github.com/rfordatascience/tidytuesday</a></p></li>
<li><p>Here is the UCI Machine Learning Repository: <a href="https://archive.ics.uci.edu/ml/index.php" class="uri">https://archive.ics.uci.edu/ml/index.php</a></p>
<ul>
<li>See also <a href="https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data" class="uri">https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data</a></li>
</ul></li>
<li><p>Here is another good general place to look: <a href="https://www.kaggle.com/datasets" class="uri">https://www.kaggle.com/datasets</a></p></li>
<li><p>To help narrow your search down or to see interesting variable ideas, check out <a href="https://www.tylervigen.com/spurious-correlations" class="uri">https://www.tylervigen.com/spurious-correlations</a>. This is the spurious correlations website, and it is fun, but if you look at the bottom of each plot you will see sources for the data. This is a good place to find very general data (or at least get a sense of where you can scrape data together from)!</p></li>
<li><p>If you are interested in medical data, check out www.countyhealthrankings.org</p></li>
<li><p>If you are interested in scraping UT data, they make <em>loads</em> of data public (e.g., beyond just professor CVs and syllabi). Check out all the data that is available in the statistical handbooks: <a href="https://reports.utexas.edu/statistical-handbook" class="uri">https://reports.utexas.edu/statistical-handbook</a></p></li>
</ul>
<div id="broader-data-sources" class="section level5">
<h5>Broader data sources:</h5>
<p><a href="www.data.gov">Data.gov</a> 186,000+ datasets!</p>
<p><a href="Social%20Explorer">Social Explorer</a> is a nice interface to Census and American Community Survey data (more user-friendly than the government sites). May need to sign up for a free trial.</p>
<p><a href="www.bls.gov">U.S. Bureau of Labor Statistics</a></p>
<p><a href="www.census.gov">U.S. Census Bureau</a></p>
<p><a href="www.gapminder.org/data">Gapminder</a>, data about the world.</p>
<p>...</p>
</div>
</div>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
